pipeline {
   agent any

   environment {
      BASE_DIR="${env.WORKSPACE}/5.6.4/"
   }
   stages {
      stage('checkout') {
          steps {
              checkout scm
          }
      }
      stage('Build') {
         steps {
            sh 'cd ${BASE_DIR}/server/ && docker build . -t terracota-oss-server-5.6.4'
             sh 'docker ps -a' 
         }

         post {
            // If Maven was able to run the tests, even if some of the test
            // failed, record the test results and archive the jar file.
            success {
               echo 'success'
            }
         }
      }
   }
}
