pipeline {
   agent any

   stages {
      stage('checkout') {
          steps {
              checkout scm
          }
      }
      stage('Build') {
         steps {
             echo 'hello world'
         }

         post {
            // If Maven was able to run the tests, even if some of the test
            // failed, record the test results and archive the jar file.
            success {
               echo 'success'
            }
         }
      }
   }
}
